---
- name: run optional versionscheck
  include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install sshfs package
  become: true
  ansible.builtin.package:
    name: sshfs
    state: present

- name: optionally manage ssh private keys
  ansible.builtin.include_tasks: manage_ssh_privkeys.yml
  when: manage_private_ssh_keys | bool

- name: optionally manage ssh config
  ansible.builtin.include_tasks: manage_ssh_config.yml
  when: manage_ssh_config | bool

- name: create directory for fuse/sshfs
  become: true
  become_user: "{{ sshfs_local_user }}"
  ansible.builtin.file:
    path: "{{ item.local }}"
    state: directory
    owner: "{{ sshfs_local_user }}"
    group: "{{ sshfs_local_user }}"
    mode: 0755
  with_items: "{{ sshfs }}"

- name: mounting fuse
  become: true
  become_user: "{{ sshfs_local_user }}"
  ansible.posix.mount:
    path: "{{ item.local }}"
    src: "sshfs#{{ item.user }}@{{ item.server }}:{{ item.remote }}"
    fstype: fuse
    state: mounted
  with_items: "{{ sshfs }}"

- name: optionally setup cron to remount fuse
  become: true
  ansible.builtin.cron:
    name: remount files
    minute: '1'
    hour: '0'
    job: 'mount -a'
    cron_file: '/etc/crontab'
    user: "{{ sshfs_local_user }}"
  when: cron_mount_fuse | bool
