---
- name: cleanup .ssh/config
  become: true
  become_user: "{{ sshfs_local_user }}"
  ansible.builtin.file:
    path: "{{ sshfs_local_home }}.ssh/config"
    state: absent
  changed_when: false

- name: "create entry for {{ item.server }} in .ssh/config"
  become: true
  become_user: "{{ sshfs_local_user }}"
  ansible.builtin.lineinfile:
    path: "{{ sshfs_local_home }}.ssh/config"
    line: "Host {{ item.server }}\n  UserKnownHostsFile=/dev/null\n  StrictHostKeyChecking no"
    create: true
    mode: 0644
  with_items: "{{ sshfs }}"
  changed_when: false

- name: create basic ssh config
  become: true
  become_user: "{{ sshfs_local_user }}"
  ansible.builtin.lineinfile:
    path: "{{ sshfs_local_home }}.ssh/config"
    line: "Host *\n  StrictHostKeyChecking {{ default_strict_host_key_checking }}"
    create: true
    mode: 0644
  changed_when: false
